### ISSUE TITLE
Erreurs d'installation

### ISSUE THREAD

**Issue by narduin** [lagreve/grevons#1]
Bonjour !

Y a-t-il des versions spécifiques ou des outils particuliers à installer pour faire fonctionner le projet ?
J'ai vu qu'il fallait utiliser node 8.9.4 mais j'ai quand même ces erreurs à l'installation:
```bash
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/Users/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Users/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/Users/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/Users/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 817, in Write
    mac_bundle_deps, extra_outputs, part_of_all)
  File "/Users/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1453, in WriteTarget
    lambda p: Sourceify(self.Absolutify(p)))
  File "/Users/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 809, in GetLdflags
    archs = self.GetActiveArchs(self.configname)
  File "/Users/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/Users/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Users/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/user/.nvm/versions/node/v8.9.4/bin/node" "/Users/user/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Documents/perso/grevons/node_modules/fsevents
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

Et ces erreurs quand je lance un `npm start` :
```bash
> grevons@ start /Users/user/Documents/perso/grevons
> meteor run

sh: meteor: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! grevons@ start: `meteor run`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the grevons@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-01-14T08_20_53_339Z-debug.log
```

Je suis sous macOS 10.13.6, j'ai les command line tools installés mais pas Xcode en entier. D'après [ce lien](https://github.com/nodejs/node-gyp/issues/569#issuecomment-255589932) ce n'est pas censé poser de problème mais sans garantie de mon côté.
D'après la doc de [meteor,](https://www.meteor.com/install) Xcode est uniquement nécessaire pour du développement iOS.
Merci !

**Comment by lagreve** [comment]
Bonjour,
A ma connaissance vous n'avez pas besoin d'outils complémentaires. Suivre la doc de meteor pour l'installation devrait faire l'affaire.
Le projet marche aussi avec nodejs v10.XX. Donc pas de restriction de ce coté la, du moins sur linux et windows.

Il semble effectivement que votre problème soit lié à Xcode.
Pourriez-vous tenté d'appliquer une des solutions listées ici et me faire un retour:
https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error

Cordialement,

**Comment by narduin** [comment]
N'étant pas familier avec meteor, je ne l'avais pas installé au préalable. Peut-être faudrait-il ajouter cette étape dans le readme :)
Merci !
